import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import IntentCircles from '../components/IntentCircles'
import { ContextProvider } from '../context/Context'
import Search from '../components/Search'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ContextProvider>
          <Search />
        </ContextProvider>
        {/* <IntentCircles intents={['a', 'b', 'c']} /> */}
      </main>
    </>
  )
}
